version: '3.7'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-sqlite
    ports:
      - "8000:8000"
    volumes:
      - ./django:/bank_manager
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        python manage.py test --failfast manager authentication &&
        coverage run --source='./manager' manage.py test &&
        coverage report &&
        coverage html &&
        python manage.py runserver 0.0.0.0:8000
      "
    user: root
    env_file:
      - .env
    depends_on:
      - rabbitmq

  celery:
    build:
      context: .
      dockerfile: Dockerfile-sqlite
    command: celery --app=bank_manager worker --loglevel=info
    environment:
      DEBUG: 1
    env_file:
      - .env
    volumes:
      - ./django:/bank_manager
    depends_on:
      - django
      - rabbitmq

  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"
