# Generated by Django 4.1.5 on 2024-02-03 18:47

from django.db import migrations
from authentication.models import User

def add_superuser(apps, schema_editor):
    User.objects.create_superuser('admin@admin.com', 'admin')


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RunPython(add_superuser)
    ]
